[package]
name = "deltek-stamp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard = "0.5.0"
chrono = "0.4"

[[bin]]
name = "ds"
path = "src/main.rs"
